version: '2'
services:
    nginx:
        image: nginx:latest
        environment:
            - TERM=xterm
        ports:
            - "1000:1000"
            - "1001:1001"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/acai-list.conf:/etc/nginx/conf.d/acai-list.conf
            - ./docker/php/index.php:/www/index.php
            - ./../myLists:/www/myLists
        links:
            - php
    php:
        image: tuxmate/php:5.5.9
        environment:
            - TERM=xterm
        volumes:
            - ./docker/php/www.conf:/etc/php5/fpm/pool.d/www.conf
            - ./docker/php/php.ini:/etc/php5/fpm/php.ini
            - ./docker/php/index.php:/www/index.php